private["_filter"];
_filter = [_this,0,0,[0]] call BIS_fnc_param;
ctrlSetText[3103,"Clothing Shop"];
switch (_filter) do
{
	case 0: {[["jamie_Adidas",nil,45],["jamie_poloamerica",nil,45],["jamie_poloapple",nil,45],["jamie_poloaustralia",nil,45],["jamie_avengers",nil,45],["jamie_polocanda",nil,45],["jamie_Ciggy",nil,45],["jamie_polococacola",nil,45],["jamie_Coco",nil,45],["jamie_polocookiemonster",nil,45],["jamie_drunk",nil,45],["jamie_poloface",nil,45],["jamie_Feature",nil,45],["jamie_fuckit",nil,45],["jamie_pololove",nil,45],["jamie_jeff",nil,45],["jamie_kappa",nil,45],["jamie_married",nil,45],["jamie_marvel",nil,45],["jamie_mexicantroll",nil,45],["jamie_poloangelo",nil,45],["jamie_minion",nil,45],["jamie_monstercat",nil,45],["jamie_polomrbong",nil,45],["jamie_nike",nil,45],["jamie_pancake",nil,45],["jamie_polomoon",nil,45],["jamie_poloqantas",nil,45],["jamie_ReclaimJoey",nil,45],["jamie_shield",nil,45],["jamie_Snoopy",nil,45],["jamie_polostunt",nil,45],["jamie_tux",nil,45],["jamie_twitch",nil,45],["U_ALR_Suit_1",nil,2000],["U_ALR_Suit",nil,2000],["U_ALR_Suit_4",nil,2000],["U_C_Driver_1_black",nil,250],["U_C_Driver_1_blue",nil,250],["U_C_Driver_1_green",nil,250],["U_C_Driver_1_orange",nil,250],["U_C_Driver_1_red",nil,250]];};
	case 1: {[["A3L_Legoman","Lego Helmet",100],["A3L_soa_helmet","Biker Helmet",400],	["A3L_gangster_hat","Gangster Mask",100],["A3L_Mask","Mask",100],["A3L_longhairblack","Long Hair Black",120],["A3L_longhairblond","Long Hair Blond",120],["A3L_longhairbrown","Long Hair Brown",120],["A3L_Crown","Crown",120],["cowboyhat","Cowboyhat",120],["A3L_mexicanhat","Mexican Hat",120],["santahat","Santa hat",120],["A3L_Sombrero","Sombrero",120],["turban","Turban",120],["A3L_russianhat","Russianhat",120],["H_Cap_tan",nil,120],["H_Cap_blk",nil,120],["H_Cap_blk_CMMG",nil,120],["H_Cap_brn_SPECOPS",nil,120],["H_Cap_tan_specops_US",nil,120],["H_Cap_khaki_specops_UK",nil,120],["H_Cap_grn",nil,120],["H_Cap_grn_BI",nil,120],["H_Cap_blk_Raven",nil,120],["H_Cap_blk_ION",nil,120],["H_RacingHelmet_1_black_F",nil,120],["H_RacingHelmet_1_blue_F",nil,120],["H_RacingHelmet_1_green_F",nil,120],["H_RacingHelmet_1_orange_F",nil,120],["H_RacingHelmet_1_red_F",nil,120]];};
	case 2: {[["G_Shades_Black",nil,25],["G_Shades_Blue",nil,20],["G_Sport_Blackred",nil,20],["G_Sport_Checkered",nil,20],["G_Sport_Blackyellow",nil,20],["G_Sport_BlackWhite",nil,20],["G_Squares",nil,10],["G_Aviator",nil,100],["G_Lady_Mirror",nil,150],["G_Lady_Dark",nil,150],["G_Lady_Blue",nil,150],["G_Lowprofile",nil,30],["G_Combat",nil,55]];};
	case 3: {[];};
	case 4: {[["B_AssaultPack_cbr",nil,2500],["B_Kitbag_mcamo",nil,4500],["B_TacticalPack_oli",nil,3500],["B_FieldPack_ocamo",nil,3000],["B_Bergen_sgg",nil,4500],["B_Kitbag_cbr",nil,4500],["B_Carryall_oli",nil,5000],["B_Carryall_khk",nil,5000]];};
};
